# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install robo dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Execute Robo Tests
      run: |
        python -m robot -d reports -x junit-report.xml src/sel
    

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Report                # Name of the folder
        path: reports/report.html           # Path to test results

    # Popular action to deploy to GitHub Pages:
    # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: reports/
        publish_branch: gh-pages
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch:
        # https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # The GH actions bot is used by default if you didn't specify the two fields.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
    
    # - name: Report- Download artifacts 
    #   run: |
    #     cd reports
    #     echo "Downloading artifcats of report"
    
    # - name: Report- Publish Report
    #   uses: actions/upload-artifact@v2
    #   with: 
    #     name: asset-reports
    #     path: reports







    # - name: Upload tests
    #   uses: joonvena/robotframework-docker-action@v1.0
    # - name: Upload test results
    #   uses: actions/upload-artifact@v1
    #   #if: always()
    #   with:
    #     name: reports
    #     path: reports