# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install robo dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Execute Robo Tests
      run: |
        python -m robot --agrumentfile ./arg_gitaction.robot
    
    
    # - name: Upload tests
    #   uses: joonvena/robotframework-docker-action@v1.0
    # - name: Upload test results
    #   uses: actions/upload-artifact@v1
    #   if: always()
    #   with:
    #     name: reports
    #     path: reports